apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  ports:
  # - name: "80"
  - port: 8100
    targetPort: 80
    protocol: "TCP"
  selector:
    service: frontend